project1/project1/urls.py
from django.conf.urls import url
from django.contrib import admin
from app1 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/$', views.home,  name="homepage"),
    url(r'^blogposts/$', views.posts,  name="blogpage"),
    url(r'^blogposts/(?P<post_id>[0-9]{1,4})/$',views.post_link, name="bloglinks") 
]

project1/app1/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

project1/app1/views.py
from django.shortcuts import render
from app1.models import Post 
from django.contrib.auth.models import User


# Create your views here.
def home(request):
	if request.method == "GET":
		return render(request, 'blog.html')
	else:
		post = publish(request)
		posts = grab_all_posts()
		context = dict()
		context['posts'] = posts
		return render(request, 'blogposts.html', context)

def posts(request):
	posts = grab_all_posts()
	context = dict()
	context['posts'] = posts
	return render(request, 'blogposts.html', context)


def publish(request):
	post = Post()
	post.author = User.objects.get(id=request.POST['author'])
	post.title = request.POST['title']
	post.text = request.POST['text']
	post.created_date = request.POST['created_date_0']
	post.published_date = request.POST['published_date_0']
	post.save()

	return post

def grab_all_posts():
	posts = Post.objects.all()
	return posts

def post_link(request, post_id):
	post = Post.objects.get(id=post_id)
	context = dict()
	context['post'] = post
	return render(request, 'posts.html', context)

project1/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Shilpi's blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
    <div class="page-header">
        <h1><a href="/">Shilpi's Blog</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

project1/templates/blog.html
<html lang="en-us" >
<head>
<title>Add post </title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.min.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-app1 model-post change-form"
  data-admin-utc-offset="19800">

     
    

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Add post</h1>
        <div id="content-main">



<form enctype="multipart/form-data" action="/home/" method="post" id="post_form" novalidate>{% csrf_token %}
<div>







  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-author">
            
            
                <div>
                    
                    
                        <label class="required" for="id_author">Author:</label>
                        
                            
<div class="related-widget-wrapper">
    <!--<select id="id_author" name="author">
<option value="" selected="selected">---------</option>
<option value=>shilpi_bose</option>
</select>-->
<input class="vTextField" id="id_author" maxlength="200" name="author" type="text" />
    
        
        <a class="related-widget-wrapper-link change-related" id="change_id_author"
            data-href-template="/admin/auth/user/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected user">
            <img src="/static/admin/img/icon-changelink.svg" alt="Change"/>
        </a>
        
        
        <a class="related-widget-wrapper-link add-related" id="add_id_author"
            href="/admin/auth/user/add/?_to_field=id&amp;_popup=1"
            title="Add another user">
            <img src="/static/admin/img/icon-addlink.svg" alt="Add"/>
        </a>
        
        
    
</div>

                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-title">
            
            
                <div>
                    
                    
                        <label class="required" for="id_title">Title:</label>
                        
                            <input class="vTextField" id="id_title" maxlength="200" name="title" type="text" />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-text">
            
            
                <div>
                    
                    
                        <label class="required" for="id_text">Text:</label>
                        
                            <textarea class="vLargeTextField" cols="40" id="id_text" name="text" rows="10">
</textarea>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-created_date">
            
            
                <div>
                    
                    
                        <label class="required" for="id_created_date_0">Created date:</label>
                        
                            <p class="datetime">Date: <input class="vDateField" id="id_created_date_0" name="created_date_0" size="10" type="text" value="2016-02-07" /><br />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-published_date">
            
            
                <div>
                    
                    
                        <label for="id_published_date_0">Published date:</label>
                        
                            <p class="datetime">Date: <input class="vDateField" id="id_published_date_0" name="published_date_0" size="10" type="text" /><br />
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />
</div>



</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

project1/templates/blogposts.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<html>
    <body>
        {% for post in posts %}
        <div>
            <a href="/blogposts/{{post.id}}/"><h2>{{post.title}}</h2></a>
            <p>{{post.published_date}}</p><br>
            <p>{{post.text}}</p>
            - {{post.author}}
        </div>
        {% endfor %}
    </body>
</html>
{% endblock %}

project1/templates/posts.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<html>
    <body>
        <div>
            <h1>Django Girls Blog</h1>
        </div>

        <div>
            <h2>{{post.title}}</h2>
            <p>{{post.published_date}}</p>
            <p>{{post.text}}</p><br>
            - {{post.author}}
        </div>
    </body>
</html>
{% endblock %}